### ISSUE TITLE
Add docs for messages and core functions

### ISSUE THREAD

**Issue by mhchia** [mhchia/js-smp#2]
### What is wrong?

Per the suggestion https://github.com/mhchia/js-smp/pull/1#discussion_r418317647, we lack explanations for messages, types, and functions, especially the ones specified in [OTR v3 spec](https://otr.cypherpunks.ca/Protocol-v3-4.1.1.html).

#### Data types
- [x] Bytes (BYTE)
- [x] Shorts (SHORT)
- [x] Ints (INT)
- [x] Multi-precision integers (MPI)

#### Messages
- [x] TLV
- [x] SMP Message TLV
- [x] SMP Message 1
- [x] SMP Message 2
- [x] SMP Message 3
- [x] SMP Message 4
- [ ] (?) SMP Abort Message(which is not implemented currently. In the current design, we terminate the connection directly to indicate we stop running the protocol)
  
#### Functions
- [x] SMP Hash function

**Comment by lsankar4033** [comment]
thanks for documenting specifics here!
